version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    networks:
      - proxy
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
      ADMIN_TOKEN: ${VW_ADMIN_TOKEN}
    volumes:
      - /path/to/vaultwarden/data:/data
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bitwarden.entrypoints=http"
        - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.local.example.com`)"
        - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
        #- "traefik.http.routers.bitwarden-secure.middlewares=authelia@docker"
        - "traefik.http.routers.bitwarden.middlewares=bitwarden-https-redirect"
        - "traefik.http.routers.bitwarden-secure.entrypoints=https"
        - "traefik.http.routers.bitwarden-secure.rule=Host(`bitwarden.local.example.com`)"
        - "traefik.http.routers.bitwarden-secure.tls=true"
        - "traefik.http.routers.bitwarden-secure.service=bitwarden"
        - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
        
networks:
  proxy:
    external: true