version: '3.0'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    networks:
      - proxy
    volumes:
      - ${VOLUME_TARGET}:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.entrypoints=http"
        - "traefik.http.routers.nextcloud.rule=Host(`${LOCAL_HOST}`)"
        - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
        - "traefik.http.routers.nextcloud-secure.entrypoints=https"
        - "traefik.http.routers.nextcloud-secure.rule=Host(`${LOCAL_HOST}`)"
        - "traefik.http.routers.nextcloud-secure.tls=true"
        - "traefik.http.routers.nextcloud-secure.service=nextcloud"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
    
networks:
  proxy:
    external: true